name: Deploy to EC2 (Build on EC2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            
            echo "---- Pulling latest code ----"

            # Clone or update repo in ~/custome_model
            if [ ! -d ~/custome_model ]; then
              git clone https://github.com/uctconsulting12/custome_model.git ~/custome_model
            else
              cd ~/custome_model
              git pull origin main
            fi

            echo "---- Building Docker image ----"
            cd ~/custome_model
            sudo docker build -t custome_image .
            echo "--- remove none images ------"
            sudo docker image prune -f

            echo "---- Stopping old container ----"
            sudo docker stop custome_container || true
            sudo docker rm custome_container || true

            echo "---- Running new container with AWS creds, GPU, volumes ----"
            sudo docker run -d \
            --name custome_container \
            --gpus all \
            --shm-size=8g \
            -p 8005:8005 \
            -v /home/ubuntu/.aws:/root/.aws \
            -v /home/ubuntu/custome_model_training/dataset:/app/dataset \
            -v /home/ubuntu/custome_model_training/runs:/app/runs \
            custome_image


            echo "Deployment completed. "
